---
- name: CHMOD WebServer - Open
  hosts: ansible
  gather_facts: False
  vars_files:
    - vars/f5_vars.yml
  roles: 
    - permissions_change

- hosts: lb
  connection: local
  gather_facts: false
  vars_files:
    - vars/f5_vars.yml
  roles:
    - install_do
    - install_asm
    - existing_policy
    - waf_block_ip
    - waf_block_urls
    - checksum
    - apply_as3

- name: CHMOD WebServer - Close
  hosts: ansible
  gather_facts: False
  vars_files:
    - vars/f5_vars.yml
  roles: 
    - permissions_change