- name: pull juicebox image
  containers.podman.podman_image:
    name:  docker.io/bkimminich/juice-shop:latest

- name: start juicebox container
  containers.podman.podman_container:
    name: juice-shop-app
    image: docker.io/bkimminich/juice-shop:latest
    expose:
      - "3000:3000"
    state: started
    restart: yes

