---
#- import_playbook: "{{playbook_dir}}/Re-Install-AS3.yaml"

- name: AS3 Tenant
  hosts: lb
  connection: httpapi
  gather_facts: false

  vars:
    pool_members: "{{ groups['web'] }}"
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_port: "{{ server_port }}"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    as3_tenant_name: "WorkshopExample"

  tasks:
    - name: CREATE AS3 JSON BODY
      set_fact:
        as3_app_body: "{{ lookup('template', 'j2/as3_template.j2', split_lines=False) }}"

    - name: PUSH AS3 Template
      f5networks.f5_bigip.bigip_as3_deploy:
        content: "{{ lookup('template','j2/tenant_base.j2', split_lines=False) }}"

    - debug:
        msg: "If the Above AS3 Fails try running the Re-Install-AS3.yaml playbook then retry"