---

- name: Obtain the ACL for a specific folder
  ansible.posix.acl:
    path: "{{ ASM_WebServer_File_Location }}"
  register: folder_output

- name: Modify Permissions of "{{ ASM_WebServer_File_Location }}" to 777
  ansible.builtin.file:
    path: "{{ ASM_WebServer_File_Location }}"
    state: directory
    mode: '0777'
  become: yes
  become_method: sudo
  become_user: root
  when: ('"r-x" in folder_output.acl[1]') and ('"1" in start')

- name: Modify Permissions of "{{ ASM_WebServer_File_Location }}" to 755
  ansible.builtin.file:
    path: "{{ ASM_WebServer_File_Location }}"
    state: directory
    mode: '0755'
  become: yes
  become_method: sudo
  become_user: root
  when: ('"rwx" in folder_output.acl[1]') and ('"0" in start')