---

- name: Obtain the ACL for a specific folder
  ansible.posix.acl:
    path: "{{ ASM_WebServer_File_Location }}"
  register: folder_output

- debug:
    var: folder_output

- debug:
    msg: READ WRITE EXECUTE
  when: folder_output.acl.group contains "rwx"

- debug:
    msg: READ EXECUTE
  when: folder_output.acl.group contains "r-x"

- name: Modify Permissions of "{{ ASM_WebServer_File_Location }}" to 755
  ansible.builtin.file:
    path: "{{ ASM_WebServer_File_Location }}"
    state: directory
    mode: '0755'
  become: yes
  become_method: sudo
  become_user: root

- name: Modify Permissions of "{{ ASM_WebServer_File_Location }}" to 755
  ansible.builtin.file:
    path: "{{ ASM_WebServer_File_Location }}"
    state: directory
    mode: '0755'
  become: yes
  become_method: sudo
  become_user: root
