---
- hosts: web
#  connection: local
  gather_facts: false
  become: yes
  vars:
    ansible_become: yes 
    ansible_become_method: sudo
    ansible_become_pass: "{{ ansible_password }}"
    ansible_python_interpreter: "/usr/libexec/platform-python"
  roles:
    - install_docker
    - install_juice_shop
    - install_nginx
