- name: Creating HTTP-Redirect for Existing Application
  hosts: web 
  connection: local
  gather_facts: false
  
#Environment variables defined
  tasks:

#Create VIP and Pool Member for Use Case

  - debug:
      var: lab_version

  - name: Test 1 (UDF)
    ansible.builtin.command: cat /etc/redhat-release
    when: 
    - lab_version is defined
    - lab_version == "udf"

  - name: Test 2 (Not Defined)
    ansible.builtin.command: cat /etc/redhat-release
    when: lab_version is not defined
    
  - name: Test 3 (Defined but not UDF)
    ansible.builtin.command: cat /etc/redhat-release
    when: 
    - lab_version is defined
    - lab_version == "provisioner"