---

#Ignore set due to Bug #1666 https://github.com/F5Networks/f5-ansible/issues/1666
- name: Restore UCS From Backup
  f5networks.f5_modules.bigip_ucs:
    ucs: "UseCase-00-backup.ucs"
    state: installed
    no_license: yes
    provider: "{{provider}}"
  delegate_to: localhost
  ignore_errors: yes
  register: restored

# - debug:
#     var: restored

- name: Restore UCS From Backup
  f5networks.f5_modules.bigip_command:
    command: 
      - load sys ucs ./var/local/ucs/UseCase-00-backup.ucs no-license
    provider: "{{provider}}"
  delegate_to: localhost
  when: restored.changed | bool
