---

- name: Get Checksum of Modified file
  ansible.builtin.stat:
    path : "{{ ASM_Policy_File }}"
  register: second_file
  when: does_xml_exist.matched >= 1
  
- name: Modified File Sha1
  ansible.builtin.set_fact:
    file2_sha: "{{ second_file.stat.checksum }}"  
  when: does_xml_exist.matched >= 1

- name: Compilation Changed
  ansible.builtin.set_fact:
    sha_matched: = "{{file2_sha and file1_sha}}"
  when:  (does_xml_exist.matched >= 1) and (file2_sha != file1_sha)

- name: Store Modified File in Webserver
  ansible.builtin.copy:
    src: "{{ ASM_Policy_File }}"
    dest: "{{ ASM_WebServer_File_Location }}{{ ASM_Final_File_Name }}"
  when:  (does_xml_exist.matched == 0) or (file2_sha != file1_sha)

- name: Modify File for Web Use
  ansible.builtin.shell: chcon -t httpd_sys_content_t {{ ASM_WebServer_File_Location }}{{ ASM_Final_File_Name }}
  when:  (does_xml_exist.matched == 0) or (file2_sha != file1_sha)
