---
- import_playbook: "{{playbook_dir}}/files/Install-DO.yaml"

- name: CHMOD WebServer - Close
  hosts: ansible
  gather_facts: False
  vars_files:
    - vars/f5_vars.yml

  tasks:

  - name: Modify Permissions of "{{ ASM_WebServer_File_Location }}" to 777
    ansible.builtin.file:
      path: "{{ ASM_WebServer_File_Location }}"
      state: directory
      mode: '0777'
    become: yes
    become_method: sudo
    become_user: root

- name: AS3 USECASE-3
  hosts: lb
  gather_facts: false
  vars: 
    ASM_Final_File_Name: "Use-Case-3-VIP-ASMPolicy-2022-12-15-20-33-52.xml"
  vars_files:
    - vars/f5_vars.yml
 
  tasks:

#   - name: PUSH AS3 Template
#     f5networks.f5_bigip.bigip_as3_deploy:
#       content: "{{ lookup('template','j2/configure_as3.j2', split_lines=False) }}"
# #    when:  (does_xml_exist.matched == 0) or (file2_sha != file1_sha) 

  - name: PUSH AS3
    ansible.builtin.uri:
      url: "https://{{ ansible_host }}:{{ server_port}}/mgmt/shared/appsvcs/declare"
      method: POST
      body: "{{ lookup('template','j2/configure_as3.j2', split_lines=False) }}"
      status_code: 200, 202
      timeout: 300
      body_format: json
      force_basic_auth: true
      user: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      validate_certs: false
    delegate_to: localhost

- name: CHMOD WebServer - Close
  hosts: ansible
  gather_facts: False
  vars_files:
    - vars/f5_vars.yml

  tasks:

  - name: Modify Permissions of "{{ ASM_WebServer_File_Location }}" to 755
    ansible.builtin.file:
      path: "{{ ASM_WebServer_File_Location }}"
      state: directory
      mode: '0755'
    become: yes
    become_method: sudo
    become_user: root