---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: CREATE NODES
      f5networks.f5_modules.bigip_node:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "{{ server_port }}"
          no_f5_teem: yes
          validate_certs: false
        host: "{{ hostvars[item].private_ip }}"
        name: "{{ hostvars[item].inventory_hostname }}"
      loop: "{{ groups['web'] }}"
