---
# tasks insttall Declaritive Onboarding Latest


- name: change Web Server based on lab
  ansible.builtin.set_fact:
    ASM_WebServer_File_Location: "{{ASM_WebServer_File_Location_2}}"
  when: lab_version is not defined

- name: Change Communication
  ansible.builtin.set_fact:
    ansible_connection: httpapi

- name: PUSH AS3 Template
  f5networks.f5_bigip.bigip_as3_deploy:
    content: "{{ lookup('template','configure_as3.j2', split_lines=False) }}"

- name: Set finished to 1
  ansible.builtin.set_fact:
    finished: 1
